name: "Hello Actions"
description: "Greet someone"
inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "docker://vinay0807/shopping"
  args:
    - ${{ inputs.MY_NAME }}
